### ISSUE TITLE
Branding repository

### ISSUE THREAD

**Issue by nickserv** [rit-sse/problems#10]
The SSE should have a branding repository for PR, companies hosting events with the SSE, members and professors who want to tell people about the SSE, project teams who want their projects to look and feel like they're from the SSE, etc.
## Idea

There would be a public GitHub repo called `branding` with the following:
- A readme with an updated public version of the SSE's existing branding guide (and it could replace it if there isn't a need for private information).
- SVG/PNG/etc. versions of the SSE logo, along with usage information
- Licensing information, along with appropriate copyrights.
- PR contact information.
- Maybe some web components and CSS stylesheets to help people build apps and sites for the SSE.

The [RIT Identity Guide](http://www.rit.edu/upub/pdfs/identity_manual.pdf) may be useful for inspiration.

**Comment by MorganCabral** [comment]
@nicolasmccurdy Rename this a design brief.

**Comment by nickserv** [comment]
I'm renaming this back to a branding repo, since we need both a branding repo and a design brief. 

However, I'm also going to close this issue because it doesn't need to be in the `problems` repo. I am  working on a (for now, private) branding repository. This information will be moved over there.
