### ISSUE TITLE
Smaller White Boards For Mentors

### ISSUE THREAD

**Issue by ethanjurman** [rit-sse/problems#12]
It would be less cumbersome for mentors (when working with one student) if we have a supply of smaller white boards for mentoring and projects. For larger groups the white boards on wheels are fantastic, but for just one person, [these](http://www.amazon.com/Chenille-Kraft-9881-10-Dry-Erase-Melamine/dp/B000CD4CXQ/ref=sr_1_2?ie=UTF8&qid=1410464542&sr=8-2&keywords=white+boards) would be fantastic.

**Comment by bbesmanoff** [comment]
I'm definitely on board (no pun intended) with the idea.  Once students get past recursion / turtle, we don't really need the full-size whiteboards all that often.

**Comment by mrm9084** [comment]
I was not able to find these at BJ's. I will look again next week.

**Comment by evajurman** [comment]
Would it be possible for the sse to purchase some from amazon?
