### ISSUE TITLE
Meetings Slides are unavailable outside the meeting

### ISSUE THREAD

**Issue by JRJurman** [rit-sse/problems#13]
People who can't make the meetings don't have a way to see what's happening!

**Comment by kaylaerdmann** [comment]
I could post them, but there's also things like the event board that shows what's happening. What would be the benefit of the slides?

**Comment by kristenmills** [comment]
I agree with kayla on this one.

**Comment by JRJurman** [comment]
Fair enough... Things like projects aren't up there, but I guess when we have a more formal meeting times that will be solved...
