### ISSUE TITLE
Resume Critique Session

### ISSUE THREAD

**Issue by brianto** [rit-sse/problems#17]
SSE usually hosts this sometime near the career fair, and it may be helpful for cs/se 2nd and 3rd years since we are usually good at picking out technical things, focus on projects, yadda yadda yadda.

**Comment by bbesmanoff** [comment]
Agreed.  Would you like to see a completely separate event, or should this be a service we ask of the older members in the lab (announced during the general meeting)?

**Comment by brianto** [comment]
> Would you like to see a completely separate event, or should this be a service we ask of the older members in the lab

Not sure. :smile:

With a one-time event, if it doesn't match your schedule or you're doing something else that day, well oops. Those people won't be able to reap the benefit. Then again, it's an established time, so maybe more people will come or plan to have their resume polished by then. If we do choose this route, perhaps we can do the resume review around the same time as or after the mock technical interview stuff on Sunday.

With an ongoing thing, perhaps that since it spans a longer time, more people will come overall. Plus, people can work around their schedule, so if they can't get a resume for us to look at until Monday, well that's cool too.

The goal in my opinion is to spread the word that upperclassmen (or whoever went on co-op) are generally great resources for resume critique and that people _should_ get their resume critiqued/proof-read before spamming it in the career fair.

_Aside: I bring this up because I started asking friends about the career fair and some realized that they haven't updated their resume in a while._

**Comment by bbesmanoff** [comment]
> perhaps we can do the resume review around the same time as or after the mock technical interview stuff on Sunday.

What if we were to say that interviewees should bring a resume with them to the mock interviews?  If we are already planning on pairing people with older members who feel comfortable interviewing, we can just reserve a few minutes of each interview for a quick glance over.

> The goal in my opinion is to spread the word that upperclassmen (or whoever went on co-op) are generally great resources for resume critique and that people should get their resume critiqued/proof-read before spamming it in the career fair

This is definitely something that we should announce on Friday at the meeting

**Comment by brianto** [comment]
@bbesmanoff sgtm

**Comment by brianto** [comment]
Malachowsky has a resume workshop on Monday and the announcement has been made. I think this is closable. :smile:

**Comment by nickserv** [comment]
I'll consider this done, since Malachowsky had his review session and some members are willing to check resumes whenever.
