### ISSUE TITLE
SSE-branded playmats

### ISSUE THREAD

**Issue by brianto** [rit-sse/problems#18]
Something like this: http://www.amazon.com/Magic-Gathering-Playmat-Dragons-Initiative/dp/B00CJDR2CA

...but SSE-branded. Since card games are sometimes played here, it may be a cool simple project.

**Comment by kristenmills** [comment]
Idk. Talk to metcalf and we could probably consider it if people actually seem to want that. Personally, I'm not thinking it is going to be popular enough to be worth buying but if you think it is, ask around.

**Comment by JRJurman** [comment]
This almost sounds like Projects... maybe we should forward this to the SSE CARD GAME team...

**Comment by brianto** [comment]
Agreed. Or "art", amiright @kristenmills? :smile:

**Comment by weswigham** [comment]
http://www.inkedplaymats.com/products/custom-playmat

These guys do quality playmats if you guys are still interested - we don't need to do any kind of bulk order, and their pricing is perfectly reasonable (for playmats). They do offer some other sizes, too.

If this is now an issue of simply making cool playmat sized artwork, I think it'll be fine to close the issue.

**Comment by JRJurman** [comment]
I concur
