### ISSUE TITLE
Front TV Error

### ISSUE THREAD

**Issue by mrm9084** [rit-sse/problems#20]
Unresponsive script. Found it this morning.

**Comment by nickserv** [comment]
I have some minor performance improvements that I'm planning on rolling out soon (probably by tomorrow). If there are still issues after that, we (the website committee) will consider the ramifications of rolling back torque.

**Comment by nickserv** [comment]
By the way, feel free to assign this issue to me.

**Comment by nickserv** [comment]
We're back on Momentum, this should be fixed.
