### ISSUE TITLE
No Food

### ISSUE THREAD

**Issue by JRJurman** [rit-sse/problems#33]
![insta](https://cloud.githubusercontent.com/assets/326557/7460317/1806e45e-f270-11e4-9e20-5b00b2770df3.gif)

**Comment by kristenmills** [comment]
Do we have food?

**Comment by weswigham** [comment]
We do.

Possibly too much.

Make it go away.

But still pay us.

**Comment by kristenmills** [comment]
:+1:

**Comment by mrm9084** [comment]
I think it is the correct amount for 3 weeks
