### ISSUE TITLE
Hang Whiteboard

### ISSUE THREAD

**Issue by robmcl4** [rit-sse/problems#4]
The new whiteboard needs to be hung in the lab near the door.

Currently this is FMS Project Request #087587

**Comment by kristenmills** [comment]
Can we hang the whiteboard by the GTV instead?

**Comment by robmcl4** [comment]
If the measurements work out I'm fine with that.

The only objection I can think of right now is that people may have to lean over the table to write on the whiteboard. But that's still a problem when hanging it by the door, because it'll be behind the rolly whiteboards and the "computer bar".

Also, FYI this is FMS Project Requset [#087587](https://facilities.rit.edu/projectrequests/controller.cfc?method=cmdViewProjectRequest&s_projectrequest_number=087587). I emailed FMS for a status update this morning, no response yet.
