### ISSUE TITLE
Add table to back of room

### ISSUE THREAD

**Issue by computermatt** [rit-sse/problems#5]
Add/move a table (or add a podium) to the back of the room that goes perpendicular to the current tables so presenters have a space to put their laptop so they can do demos and face the front of the room.

**Comment by kristenmills** [comment]
I think a podiums sounded promising. We will see.

**Comment by kristenmills** [comment]
Brad is going to talk to Sarah about a podium

**Comment by robmcl4** [comment]
For the record, we just picked up one of the free drawing tables today.

**Comment by brianto** [comment]
@robmcl4 why is this reopened? Is it because the table may go away soon?

**Comment by mrm9084** [comment]
we are looking into getting a podium

**Comment by kristenmills** [comment]
Got a podium
