### ISSUE TITLE
Buy hand sanitizer

### ISSUE THREAD

**Issue by brianto** [rit-sse/problems#8]
For example, this: http://www.amazon.com/Purell-Hand-Sanitizer-Original-LT/dp/B0085TFDHI

**Comment by kristenmills** [comment]
My bad wasn't purchased

**Comment by mrm9084** [comment]
Why is this a need? Soap works better than hand sanitizer. http://www.cdc.gov/handwashing/show-me-the-science-hand-sanitizer.html

**Comment by brianto** [comment]
If soap works better, then can we buy soap that doesn't require water?

I see it as a convenience, so that we don't need to run into the bathroom to wash our hands if, say hamburger juice leaks onto our hands and napkins don't take care of all the residue (the "sticky feeling").

To be honest, I don't recall many people using the hand sanitzer back when we had a giant bottle.

If you don't see a need, can you mark this as `wontfix`. :smiley:

**Comment by kristenmills** [comment]
I think we should get it for what it's worth

**Comment by nickserv** [comment]
I agree. Hand sanitizer is better than nothing, and you could always walk to the bathroom if you don't want to use it.

**Comment by brianto** [comment]
Any updates on this?

**Comment by mrm9084** [comment]
Did not go out shopping last week.

**Comment by mrm9084** [comment]
Also Upkeep has to approve. This goes towards his budget.

**Comment by mrm9084** [comment]
I was not able to find this at BJs. I will try looking again next week.

**Comment by nickserv** [comment]
@mrm9084 Is this done?

**Comment by brianto** [comment]
Looks like this is done. There's some at the front desk.
